<a href="https://colab.research.google.com/github/Vemula-Meenakshi/Rock-paper-scissors-game/blob/main/iris_flower_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [ ]:
df=pd.read_csv("Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
X=df
X=X.drop("Species",axis=1)
y=df["Species"]
print(X.head())
print(y.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2
0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
print(X_train)
print("\nScaled Test Set:")
print(X_test)
print("Scaled Training Set:")
print(X_train)
print("\ NnScaled Test Set:")
print(X_test)

[[ 0.34899193  0.31553662 -0.03612186  0.44748582  0.2345312 ]
 [ 1.34449565  2.2449325  -0.03612186  1.29803965  1.39642889]
 [-0.14875993 -0.2873996  -1.240184    0.0505607  -0.15276803]
 [ 1.18612006  0.67729835 -0.51774672  1.01452171  1.13822941]
 [ 0.86936888 -0.04622511 -0.51774672  0.73100376  1.52552864]
 [-0.62388671 -0.64916132  1.64956512 -1.31032543 -1.31466572]
 [-0.51076129 -0.40798684 -1.72180885  0.10726429  0.10543146]
 [-1.0763884  -0.76974857  0.92712784 -1.36702901 -1.31466572]
 [-0.4881362   0.79788559 -0.51774672  0.44748582  0.36363094]
 [ 0.73361837  1.03906007 -1.240184    1.12792888  0.75093018]
 [ 0.82411871  1.15964732 -0.03612186  0.95781812  1.13822941]
 [-1.32526433 -0.89033581  1.16794027 -1.36702901 -1.18556598]
 [ 0.9824943   0.19494938 -1.96262128  0.67430017  0.36363094]
 [ 0.62049295  0.5567111  -0.27693429  1.01452171  0.75093018]
 [-0.39763586  0.91847283 -0.27693429  0.44748582  0.10543146]
 [ 0.95986922  2.2449325  -0.99937157  1.75166836  1.39